appName: myhelmapp

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: anandkumarmk6479/webapp
  tag: latest
imagePullSecrets:
  name: regcred

service:
  type: ClusterIP
  port: 80
